name: 新的需求 | Feature Request
description: 
  为 Leaves 提供新的想法。
  Suggest an idea for Leaves.
labels:
  - "status: needs triage"
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 Leaves 提交新的需求！请尽可能详细地描述，以便我们可以更轻松地考虑和审查请求。
        Thank you for filling out a feature request for Leaves! Please be as detailed as possible so that we may consider and review the request easier.<br>
        请搜索所有问题以避免重复的功能请求。如果您期望的功能已存在，请回复如果您有什么要补充的。
        We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.<br>
        在请求新功能之前，请确保您使用的是最新版本并且您请求的功能不在 Leaves 中。
        Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already in Leaves.<br>
        我们的开发人员可能没有过多时间来测试新功能的可用性，如新功能进入 Test 状态，您可以帮助我们进行测试并回复。
        Our developers may not have much time to test the usability of new functions. If the new functions enter the Test state, you can help us test and reply.

  - type: textarea
    id: feature
    attributes:
      label: 描述你希望添加的功能。 Describe the feature you'd like.
      placeholder: e.g. 可以给指定的假人设置俯仰角和偏向角
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 其他 Other
      description: 添加其他的信息。 Add any other context or screenshots about the feature request below.
