name: Bug反馈 Bug report
description: 
  报告Bug，插件不兼容情况，以及其他相关问题。
  Report issues with plugin incompatbility or other behavior related issues.
body:
  - type: markdown
    attributes:
      value: |
        请详细描述您所遇到的Bug。确保您**真的**遇到了**服务端**Bug，而非原版特性或客户端Bug。
        Please describe the bug you encountered in detail. Make sure you're **actually** hitting a **server-side** bug, not a vanilla feature or client-side bug.
        如果您确定的话，就按照下面的模板填充信息，并提交反馈。
        If you are sure, follow the template below to fill in the information and submit your feedback.
  - type: input
    id: leavesMC-version
    attributes:
      label: 服务端版本 LeavesMC Version
      description:
        LeavesMC服务端发行版本 LeavesMC server release version (contains the git commit's hash)<br>
        通过执行`/version`命令将获取到的内容复制到这里。 Run `/version` on your server and paste the full, unmodified output here.
      placeholder: >
        e.g. git-Leaves-"d4cc9fe" (MC: 1.19) 
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 预期的行为 Expected behavior
      description: 你期望看到的情况是什么样。What you expected to see.
      placeholder: e.g. 使用 /bot remove [botname] 命令可以将假人移除
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: 观测到的实际行为 Observed/Actual behavior
      description: 你实际看到的。 What you actually saw.
      placeholder: e.g. 使用 /bot remove bot1 命令没有将假人bot1移除，假人仍在
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: 复现步骤 Steps/models to reproduce
      description:
        这里应该有一个图片、视频或其他信息来展现你的问题。<br>
        This may include a build schematic, a video, or detailed instructions to help reconstruct the issue.
      placeholder: e.g. 召唤一个假人，然后使用 /bot remove bot1 命令没有将假人移除，假人仍在
    validations:
      required: true
  - type: textarea
    id: plugin-list
    attributes:
      label: 插件与数据包列表。 Plugin and Datapack List.
      description:
        服务器上的所有插件和数据包列表。
        All plugins and datapacks running on your server.<br>
        执行命令`/plugins`查看插件列表。执行命令`/datapack list`查看数据包列表。
        To list plugins, run `/plugins`. For datapacks, run `/datapack list`.
    validations:
      required: true
  - type: textarea
    id: other
    attributes:
      label: 更多详细信息。 The more information.
