name: 新的需求 Feature Request
description: 
  为Leaves提供新的想法。
  Suggest an idea for Leaves.
body:
  - type: markdown
    attributes:
      value: |
        感谢您为Leaves提交新的需求！请尽可能详细地描述，以便我们可以更轻松地考虑和审查请求。<br>
        Thank you for filling out a feature request for Leaves! Please be as detailed as possible so that we may consider and review the request easier.<br>
        请搜索所有问题以避免重复的功能请求。如果您期望的功能已存在，请回复如果您有什么要补充的。<br>
        We ask that you search all the issues to avoid a duplicate feature request. If one exists, please reply if you have anything to add.<br>
        在请求新功能之前，请确保您使用的是最新版本并且您请求的功能不在 Leaves 中。<br>
        Before requesting a new feature, please make sure you are using the latest version and that the feature you are requesting is not already in Paper.
        
  - type: textarea
    id: feature
    attributes:
      label: 描述你希望添加的功能。 Describe the feature you'd like.
      placeholder: e.g. 可以给指定的假人设置俯仰角和偏向角
    validations:
      required: true
  - type: textarea
    id: othre
    attributes:
      label: 其他 Other
      description: 添加其他的信息。 Add any other context or screenshots about the feature request below.
