package org.leavesmc.leaves.bytebuf;

public interface PacketType {

    String id();

    Bound bound();

    enum Bound {
        SERVER, CLIENT
    }

    enum Clientbound implements PacketType {
        CLEAR_DIALOG("clientbound/clear_dialog"),
        CUSTOM_PAYLOAD("clientbound/custom_payload"),
        CUSTOM_REPORT_DETAILS("clientbound/custom_report_details"),
        DISCONNECT("clientbound/disconnect"),
        KEEP_ALIVE("clientbound/keep_alive"),
        PING("clientbound/ping"),
        RESOURCE_PACK_POP("clientbound/resource_pack_pop"),
        RESOURCE_PACK_PUSH("clientbound/resource_pack_push"),
        SERVER_LINKS("clientbound/server_links"),
        SHOW_DIALOG("clientbound/show_dialog"),
        STORE_COOKIE("clientbound/store_cookie"),
        TRANSFER("clientbound/transfer"),
        UPDATE_TAGS("clientbound/update_tags"),
        CODE_OF_CONDUCT("clientbound/code_of_conduct"),
        FINISH_CONFIGURATION("clientbound/finish_configuration"),
        REGISTRY_DATA("clientbound/registry_data"),
        RESET_CHAT("clientbound/reset_chat"),
        SELECT_KNOWN_PACKS("clientbound/select_known_packs"),
        UPDATE_ENABLED_FEATURES("clientbound/update_enabled_features"),
        COOKIE_REQUEST("clientbound/cookie_request"),
        BUNDLE("clientbound/bundle"),
        BUNDLE_DELIMITER("clientbound/bundle_delimiter"),
        ADD_ENTITY("clientbound/add_entity"),
        ANIMATE("clientbound/animate"),
        AWARD_STATS("clientbound/award_stats"),
        BLOCK_CHANGED_ACK("clientbound/block_changed_ack"),
        BLOCK_DESTRUCTION("clientbound/block_destruction"),
        BLOCK_ENTITY_DATA("clientbound/block_entity_data"),
        BLOCK_EVENT("clientbound/block_event"),
        BLOCK_UPDATE("clientbound/block_update"),
        BOSS_EVENT("clientbound/boss_event"),
        CHANGE_DIFFICULTY("clientbound/change_difficulty"),
        CHUNK_BATCH_FINISHED("clientbound/chunk_batch_finished"),
        CHUNK_BATCH_START("clientbound/chunk_batch_start"),
        CHUNKS_BIOMES("clientbound/chunks_biomes"),
        CLEAR_TITLES("clientbound/clear_titles"),
        COMMAND_SUGGESTIONS("clientbound/command_suggestions"),
        COMMANDS("clientbound/commands"),
        CONTAINER_CLOSE("clientbound/container_close"),
        CONTAINER_SET_CONTENT("clientbound/container_set_content"),
        CONTAINER_SET_DATA("clientbound/container_set_data"),
        CONTAINER_SET_SLOT("clientbound/container_set_slot"),
        COOLDOWN("clientbound/cooldown"),
        CUSTOM_CHAT_COMPLETIONS("clientbound/custom_chat_completions"),
        DAMAGE_EVENT("clientbound/damage_event"),
        DEBUG_BLOCK_VALUE("clientbound/debug/block_value"),
        DEBUG_CHUNK_VALUE("clientbound/debug/chunk_value"),
        DEBUG_ENTITY_VALUE("clientbound/debug/entity_value"),
        DEBUG_EVENT("clientbound/debug/event"),
        DEBUG_SAMPLE("clientbound/debug_sample"),
        DELETE_CHAT("clientbound/delete_chat"),
        DISGUISED_CHAT("clientbound/disguised_chat"),
        ENTITY_EVENT("clientbound/entity_event"),
        ENTITY_POSITION_SYNC("clientbound/entity_position_sync"),
        EXPLODE("clientbound/explode"),
        FORGET_LEVEL_CHUNK("clientbound/forget_level_chunk"),
        GAME_EVENT("clientbound/game_event"),
        GAME_TEST_HIGHLIGHT_POS("clientbound/game_test_highlight_pos"),
        MOUNT_SCREEN_OPEN("clientbound/mount_screen_open"),
        HURT_ANIMATION("clientbound/hurt_animation"),
        INITIALIZE_BORDER("clientbound/initialize_border"),
        LEVEL_CHUNK_WITH_LIGHT("clientbound/level_chunk_with_light"),
        LEVEL_EVENT("clientbound/level_event"),
        LEVEL_PARTICLES("clientbound/level_particles"),
        LIGHT_UPDATE("clientbound/light_update"),
        LOGIN("clientbound/login"),
        MAP_ITEM_DATA("clientbound/map_item_data"),
        MERCHANT_OFFERS("clientbound/merchant_offers"),
        MOVE_ENTITY_POS("clientbound/move_entity_pos"),
        MOVE_ENTITY_POS_ROT("clientbound/move_entity_pos_rot"),
        MOVE_MINECART_ALONG_TRACK("clientbound/move_minecart_along_track"),
        MOVE_ENTITY_ROT("clientbound/move_entity_rot"),
        MOVE_VEHICLE("clientbound/move_vehicle"),
        OPEN_BOOK("clientbound/open_book"),
        OPEN_SCREEN("clientbound/open_screen"),
        OPEN_SIGN_EDITOR("clientbound/open_sign_editor"),
        PLACE_GHOST_RECIPE("clientbound/place_ghost_recipe"),
        PLAYER_ABILITIES("clientbound/player_abilities"),
        PLAYER_CHAT("clientbound/player_chat"),
        PLAYER_COMBAT_END("clientbound/player_combat_end"),
        PLAYER_COMBAT_ENTER("clientbound/player_combat_enter"),
        PLAYER_COMBAT_KILL("clientbound/player_combat_kill"),
        PLAYER_INFO_REMOVE("clientbound/player_info_remove"),
        PLAYER_INFO_UPDATE("clientbound/player_info_update"),
        PLAYER_LOOK_AT("clientbound/player_look_at"),
        PLAYER_POSITION("clientbound/player_position"),
        PLAYER_ROTATION("clientbound/player_rotation"),
        RECIPE_BOOK_ADD("clientbound/recipe_book_add"),
        RECIPE_BOOK_REMOVE("clientbound/recipe_book_remove"),
        RECIPE_BOOK_SETTINGS("clientbound/recipe_book_settings"),
        REMOVE_ENTITIES("clientbound/remove_entities"),
        REMOVE_MOB_EFFECT("clientbound/remove_mob_effect"),
        RESPAWN("clientbound/respawn"),
        ROTATE_HEAD("clientbound/rotate_head"),
        SECTION_BLOCKS_UPDATE("clientbound/section_blocks_update"),
        SELECT_ADVANCEMENTS_TAB("clientbound/select_advancements_tab"),
        SERVER_DATA("clientbound/server_data"),
        SET_ACTION_BAR_TEXT("clientbound/set_action_bar_text"),
        SET_BORDER_CENTER("clientbound/set_border_center"),
        SET_BORDER_LERP_SIZE("clientbound/set_border_lerp_size"),
        SET_BORDER_SIZE("clientbound/set_border_size"),
        SET_BORDER_WARNING_DELAY("clientbound/set_border_warning_delay"),
        SET_BORDER_WARNING_DISTANCE("clientbound/set_border_warning_distance"),
        SET_CAMERA("clientbound/set_camera"),
        SET_CHUNK_CACHE_CENTER("clientbound/set_chunk_cache_center"),
        SET_CHUNK_CACHE_RADIUS("clientbound/set_chunk_cache_radius"),
        SET_DEFAULT_SPAWN_POSITION("clientbound/set_default_spawn_position"),
        SET_DISPLAY_OBJECTIVE("clientbound/set_display_objective"),
        SET_ENTITY_DATA("clientbound/set_entity_data"),
        SET_ENTITY_LINK("clientbound/set_entity_link"),
        SET_ENTITY_MOTION("clientbound/set_entity_motion"),
        SET_EQUIPMENT("clientbound/set_equipment"),
        SET_EXPERIENCE("clientbound/set_experience"),
        SET_HEALTH("clientbound/set_health"),
        SET_HELD_SLOT("clientbound/set_held_slot"),
        SET_OBJECTIVE("clientbound/set_objective"),
        SET_PASSENGERS("clientbound/set_passengers"),
        SET_PLAYER_TEAM("clientbound/set_player_team"),
        SET_SCORE("clientbound/set_score"),
        SET_SIMULATION_DISTANCE("clientbound/set_simulation_distance"),
        SET_SUBTITLE_TEXT("clientbound/set_subtitle_text"),
        SET_TIME("clientbound/set_time"),
        SET_TITLE_TEXT("clientbound/set_title_text"),
        SET_TITLES_ANIMATION("clientbound/set_titles_animation"),
        SOUND_ENTITY("clientbound/sound_entity"),
        SOUND("clientbound/sound"),
        START_CONFIGURATION("clientbound/start_configuration"),
        STOP_SOUND("clientbound/stop_sound"),
        SYSTEM_CHAT("clientbound/system_chat"),
        TAB_LIST("clientbound/tab_list"),
        TAG_QUERY("clientbound/tag_query"),
        TAKE_ITEM_ENTITY("clientbound/take_item_entity"),
        TELEPORT_ENTITY("clientbound/teleport_entity"),
        TEST_INSTANCE_BLOCK_STATUS("clientbound/test_instance_block_status"),
        UPDATE_ADVANCEMENTS("clientbound/update_advancements"),
        UPDATE_ATTRIBUTES("clientbound/update_attributes"),
        UPDATE_MOB_EFFECT("clientbound/update_mob_effect"),
        UPDATE_RECIPES("clientbound/update_recipes"),
        PROJECTILE_POWER("clientbound/projectile_power"),
        WAYPOINT("clientbound/waypoint"),
        RESET_SCORE("clientbound/reset_score"),
        TICKING_STATE("clientbound/ticking_state"),
        TICKING_STEP("clientbound/ticking_step"),
        SET_CURSOR_ITEM("clientbound/set_cursor_item"),
        SET_PLAYER_INVENTORY("clientbound/set_player_inventory"),
        CUSTOM_QUERY("clientbound/custom_query"),
        LOGIN_FINISHED("clientbound/login_finished"),
        HELLO("clientbound/hello"),
        LOGIN_COMPRESSION("clientbound/login_compression"),
        LOGIN_DISCONNECT("clientbound/login_disconnect"),
        PONG_RESPONSE("clientbound/pong_response"),
        STATUS_RESPONSE("clientbound/status_response")
        ;
        private final String id;

        Clientbound(String id) {
            this.id = id;
        }

        @Override
        public String id() {
            return id;
        }

        @Override
        public Bound bound() {
            return Bound.CLIENT;
        }
    }

    enum Serverbound implements PacketType {
        CLIENT_INFORMATION("serverbound/client_information"),
        CUSTOM_PAYLOAD("serverbound/custom_payload"),
        KEEP_ALIVE("serverbound/keep_alive"),
        PONG("serverbound/pong"),
        RESOURCE_PACK("serverbound/resource_pack"),
        CUSTOM_CLICK_ACTION("serverbound/custom_click_action"),
        ACCEPT_CODE_OF_CONDUCT("serverbound/accept_code_of_conduct"),
        FINISH_CONFIGURATION("serverbound/finish_configuration"),
        SELECT_KNOWN_PACKS("serverbound/select_known_packs"),
        COOKIE_RESPONSE("serverbound/cookie_response"),
        ACCEPT_TELEPORTATION("serverbound/accept_teleportation"),
        BLOCK_ENTITY_TAG_QUERY("serverbound/block_entity_tag_query"),
        BUNDLE_ITEM_SELECTED("serverbound/bundle_item_selected"),
        CHANGE_DIFFICULTY("serverbound/change_difficulty"),
        CHANGE_GAME_MODE("serverbound/change_game_mode"),
        CHAT_ACK("serverbound/chat_ack"),
        CHAT_COMMAND("serverbound/chat_command"),
        CHAT_COMMAND_SIGNED("serverbound/chat_command_signed"),
        CHAT("serverbound/chat"),
        CHAT_SESSION_UPDATE("serverbound/chat_session_update"),
        CHUNK_BATCH_RECEIVED("serverbound/chunk_batch_received"),
        CLIENT_COMMAND("serverbound/client_command"),
        CLIENT_TICK_END("serverbound/client_tick_end"),
        COMMAND_SUGGESTION("serverbound/command_suggestion"),
        CONFIGURATION_ACKNOWLEDGED("serverbound/configuration_acknowledged"),
        CONTAINER_BUTTON_CLICK("serverbound/container_button_click"),
        CONTAINER_CLICK("serverbound/container_click"),
        CONTAINER_CLOSE("serverbound/container_close"),
        CONTAINER_SLOT_STATE_CHANGED("serverbound/container_slot_state_changed"),
        DEBUG_SUBSCRIPTION_REQUEST("serverbound/debug_subscription_request"),
        EDIT_BOOK("serverbound/edit_book"),
        ENTITY_TAG_QUERY("serverbound/entity_tag_query"),
        INTERACT("serverbound/interact"),
        JIGSAW_GENERATE("serverbound/jigsaw_generate"),
        LOCK_DIFFICULTY("serverbound/lock_difficulty"),
        MOVE_PLAYER_POS("serverbound/move_player_pos"),
        MOVE_PLAYER_POS_ROT("serverbound/move_player_pos_rot"),
        MOVE_PLAYER_ROT("serverbound/move_player_rot"),
        MOVE_PLAYER_STATUS_ONLY("serverbound/move_player_status_only"),
        MOVE_VEHICLE("serverbound/move_vehicle"),
        PADDLE_BOAT("serverbound/paddle_boat"),
        PICK_ITEM_FROM_BLOCK("serverbound/pick_item_from_block"),
        PICK_ITEM_FROM_ENTITY("serverbound/pick_item_from_entity"),
        PLACE_RECIPE("serverbound/place_recipe"),
        PLAYER_ABILITIES("serverbound/player_abilities"),
        PLAYER_ACTION("serverbound/player_action"),
        PLAYER_COMMAND("serverbound/player_command"),
        PLAYER_INPUT("serverbound/player_input"),
        PLAYER_LOADED("serverbound/player_loaded"),
        RECIPE_BOOK_CHANGE_SETTINGS("serverbound/recipe_book_change_settings"),
        RECIPE_BOOK_SEEN_RECIPE("serverbound/recipe_book_seen_recipe"),
        RENAME_ITEM("serverbound/rename_item"),
        SEEN_ADVANCEMENTS("serverbound/seen_advancements"),
        SELECT_TRADE("serverbound/select_trade"),
        SET_BEACON("serverbound/set_beacon"),
        SET_CARRIED_ITEM("serverbound/set_carried_item"),
        SET_COMMAND_BLOCK("serverbound/set_command_block"),
        SET_COMMAND_MINECART("serverbound/set_command_minecart"),
        SET_CREATIVE_MODE_SLOT("serverbound/set_creative_mode_slot"),
        SET_JIGSAW_BLOCK("serverbound/set_jigsaw_block"),
        SET_STRUCTURE_BLOCK("serverbound/set_structure_block"),
        SET_TEST_BLOCK("serverbound/set_test_block"),
        TEST_INSTANCE_BLOCK_ACTION("serverbound/test_instance_block_action"),
        SIGN_UPDATE("serverbound/sign_update"),
        SWING("serverbound/swing"),
        TELEPORT_TO_ENTITY("serverbound/teleport_to_entity"),
        USE_ITEM_ON("serverbound/use_item_on"),
        USE_ITEM("serverbound/use_item"),
        CUSTOM_QUERY_ANSWER("serverbound/custom_query_answer"),
        HELLO("serverbound/hello"),
        KEY("serverbound/key"),
        LOGIN_ACKNOWLEDGED("serverbound/login_acknowledged"),
        PING_REQUEST("serverbound/ping_request"),
        STATUS_REQUEST("serverbound/status_request")
        ;
        private final String id;

        Serverbound(String id) {
            this.id = id;
        }

        @Override
        public String id() {
            return id;
        }

        @Override
        public Bound bound() {
            return Bound.CLIENT;
        }
    }
}
